### ISSUE TITLE
Typo found on README.MD

### ISSUE THREAD

**Issue by maibarra** [opencerta/issuer-cli#1]
On line **35** of _README.MD_ you can read the following:
``node index.js csr --keynName keyName --cn 'Practitioner Name' --org 'Organization Name' --country US --email practitioner@lab.organization.com csrFile.csr``

where `--keynName` should read `--keyName` for Step 2.1 to work correctly.

**Found while**: trying this out by just copying and pasting everything in here 😅 

Thanks! 
PS: Project looks awesome!

**Comment by roznoyolo** [comment]
Hi, maibarra

Thanks for spotting that, please send PR.

**Comment by ramtorr** [comment]
fixed, thanks!
